import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@shoelace-style/shoelace/dist/themes/light.css";
import ShoelaceSetup from "./shoelace-setup";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UI Demonstration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ShoelaceSetup>
          <Header />
          {children}
        </ShoelaceSetup>
      </body>
    </html>
  );
}
